services:
  postgreSQL1:
    image: postgres:17.2
    environment:
      POSTGRES_USER: "tester"
      POSTGRES_PASSWORD: "testPassword1"
    container_name: postrges1
    ports:
      - 1026:5432
    restart: always
    volumes:
      - /home/igor/"laba6/db/data:/var/lib/postgresql/data
    networks:
      CourseWorkNet:
        ipv4_address: 173.16.1.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tester -d tester"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin41:
    container_name: pgadmin41
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 1025:80
    networks:
      CourseWorkNet:
        ipv4_address: 173.16.1.7
      
volumes:
  db:
    driver: local
  postgreSQL:
    driver: local

networks:
  CourseWorkNet:
    driver: bridge
    ipam:
      config:
        - subnet: "173.16.0.0/16"
